version: '3'
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: norrisdan/php74-fpm
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: tweeter
            MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
            SERVICE_NAME: mysql
            SERVICE_TAGS: dev
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

volumes:
    dbdata:
        driver: local

networks:
    app-network:
        driver: bridge
